# Generated by Django 3.1.4 on 2020-12-16 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenThingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('theme', models.CharField(max_length=100)),
                ('idea1', models.CharField(max_length=100)),
                ('idea2', models.CharField(max_length=100)),
                ('idea3', models.CharField(max_length=100)),
                ('idea4', models.CharField(max_length=100)),
                ('idea5', models.CharField(max_length=100)),
                ('idea6', models.CharField(max_length=100)),
                ('idea7', models.CharField(max_length=100)),
                ('idea8', models.CharField(max_length=100)),
                ('idea9', models.CharField(max_length=100)),
                ('idea10', models.CharField(max_length=100)),
            ],
        ),
    ]
